## Copyright (c) 2015 SONATA-NFV, 2017 5GTANGO [, ANY ADDITIONAL AFFILIATION]
## ALL RIGHTS RESERVED.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Neither the name of the SONATA-NFV, 5GTANGO [, ANY ADDITIONAL AFFILIATION]
## nor the names of its contributors may be used to endorse or promote
## products derived from this software without specific prior written
## permission.
##
## This work has been performed in the framework of the SONATA project,
## funded by the European Commission under Grant number 671517 through
## the Horizon 2020 and 5G-PPP programmes. The authors would like to
## acknowledge the contributions of their colleagues of the SONATA
## partner consortium (www.sonata-nfv.eu).
##
## This work has been performed in the framework of the 5GTANGO project,
## funded by the European Commission under Grant number 761493 through
## the Horizon 2020 and 5G-PPP programmes. The authors would like to
## acknowledge the contributions of their colleagues of the 5GTANGO
## partner consortium (www.5gtango.eu).
# encoding: utf-8
base_path: ''
paths:
  /: 
    site: http://tng-gtk-vnv:5000/
    permissions:
    - role: '-'
      verbs: get
  /api/v3(/?): 
    site: http://tng-gtk-vnv:5000/
    permissions:
    - role: '-'
      verbs: get
  /api/v3/pings(/?): 
    site: http://tng-gtk-common:5000/pings
    permissions:
    - role: '-'
      verbs: get
  /api/v3/packages(/?|/*): 
    site: http://tng-gtk-common:5000/packages
    permissions:
    - role: admin
      verbs: 'get,delete,options,post'
    - role: developer
      verbs: 'get,delete,options,post'
  /api/v3/services(/?|/*): 
    site: http://tng-gtk-common:5000/services
    permissions:
    - role: admin
      verbs: 'get,options'
    - role: developer
      verbs: 'get,options'
    - role: customer
      verbs: 'get,options'
  /api/v3/functions(/?|/*): 
    site: http://tng-gtk-common:5000/functions
    permissions:
    - role: admin
      verbs: 'get,options'
    - role: developer
      verbs: 'get,options'
    - role: customer
      verbs: 'get,options'
  /api/v3/tests/plans/policies(/?|/*):
    site: http://tng-vnv-platform-adapter:5001/adapters/policies
    permissions:
    - role: admin
      verbs: 'get,options,post,put'
    - role: developer
      verbs: 'get,options,post,put'
  /api/v3/tests/plans(/?|/*):
    site: http://tng-vnv-planner:6100/api/v1/test-plans
    permissions:
    - role: admin
      verbs: 'get,options,post,put'
    - role: developer
      verbs: 'get,options,post,put'
  /api/v3/tests(/?|/*):
    site: http://tng-gtk-vnv:5000
    permissions:
    - role: admin
      verbs: 'get,options'
    - role: customer
      verbs: 'get,options'
    - role: developer
      verbs: 'get,options'
  /api/v3/users/roles(/?|/*):
    site: http://tng-gtk-usr:4567/roles
    permissions:
    - role: '-'
      verbs: 'get,options'
    - role: admin
      verbs: 'get,delete,options,post'
  /api/v3/users/sessions(/?|/*): 
    site: http://tng-gtk-usr:4567/login
    permissions:
    - role: '-'
      verbs: post
  /api/v3/users(/?|/*): 
    site: http://tng-gtk-usr:4567/users
    permissions:
    - role: '-'
      verbs: post
    - role: admin
      verbs: 'get,delete,options,patch,post'
    - role: customer
      verbs: 'get,delete,options,patch,post'
    - role: developer
      verbs: 'get,delete,options,patch,post'
  /api/v3/settings/platforms(/?|/*):
    site: http://tng-vnv-platform-adapter:5001/service_platforms
    permissions:
    - role: admin
      verbs: 'get,delete,options,post,patch'
  /api/v3/settings/monitoring(/?|/*):
    site: http://son-monitor-manager:8000/api/v2/prometheus/targets
    permissions:
    - role: admin
      verbs: 'get,options,post'
  /api/v3/monitoring/data(/?|/*): 
    site: http://son-monitor-manager:8000/api/v2
    permissions:
    - role: '-'
      verbs: get
    - role: admin
      verbs: 'get,options,post'
    - role: developer
      verbs: 'get,options'
  /api/v3/monitoring/graphs(/?|/*): 
    site: http://son-monitor-grafana:3000
    permissions:
    - role: '-'
      verbs: get
    - role: admin
      verbs: 'get,options,post'
    - role: developer
      verbs: 'get,options'
  /api/v3/recommendations(/?|/*): 
    site: http://tng-vnv-dsm:4010/api/v1
    permissions:
    - role: admin
      verbs: 'options,post,get,delete'
    - role: developer
      verbs: 'get,delete,options,post'
    - role: customer
      verbs: 'get'
  /api/v3/analytics(/?|/*): 
    site: http://tng-analytics-engine:8085
    permissions:
    - role: admin
      verbs: 'options,post,get,delete'
    - role: developer
      verbs: 'get,delete,options,post'
    - role: customer
      verbs: 'get'
  /api/v3/analytic/results(/?|/*): 
    site: http://tng-analytics-results:80
    permissions:
    - role: admin
      verbs: 'options,get,delete'
    - role: developer
      verbs: 'get,options,delete'
    - role: customer
      verbs: 'get'
